### ISSUE TITLE
Deprecated functions in cairo-quartz

### ISSUE THREAD

**Issue by Tilogorn** [acornejo/homebrew-quartz#9]
Running `brew update` and `brew outdated` today showed the following warnings:

```
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/acornejo/homebrew-quartz/cairo-quartz.rb:6:in `<class:CairoQuartz>'
Please report this to the acornejo/quartz tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/acornejo/homebrew-quartz/cairo-quartz.rb:6:in `<class:CairoQuartz>'
Please report this to the acornejo/quartz tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/acornejo/homebrew-quartz/cairo-quartz.rb:6:in `<class:CairoQuartz>'
Please report this to the acornejo/quartz tap!

Warning: Calling Formula.fails_with_llvm is deprecated!
There is no replacement.
/usr/local/Library/Taps/acornejo/homebrew-quartz/cairo-quartz.rb:14:in `<class:CairoQuartz>'
Please report this to the acornejo/quartz tap!
```

**Comment by hackur** [comment]
I installed the latest version of xcode beta thinking that would fix it... Didn't seem to work.

**Comment by Tilogorn** [comment]
As the new release of Homebrew is _disabling_ SHA1-Use, I can't even call the `remove`-procedure for homebrew-quartz!

```
$ brew remove cairo-quartz
```

```
Error: Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/acornejo/homebrew-quartz/cairo-quartz.rb:6:in `<class:CairoQuartz>'
Please report this to the acornejo/quartz tap!
```

That's very annoying, I will report this also to the brew developer team...
